# Generated by Django 3.2.9 on 2021-12-30 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='portfoliomodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('imaage', models.ImageField(upload_to='projectsfolio/images/')),
                ('url', models.URLField(blank=True)),
            ],
        ),
    ]
