# Generated by Django 3.2.9 on 2022-01-02 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectsfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfoliomodel',
            old_name='imaage',
            new_name='image',
        ),
    ]
